### ISSUE TITLE
No support from chrome.system.display

### ISSUE THREAD

**Issue by joanne254** [acvetkov/sinon-chrome#16]
Should probably be added, it's a pretty useful one!
Possible?

**Comment by acvetkov** [comment]
@joanne254 hi!

Thanks for issue. I'll add `chrome.system.display` namespace in 30 minutes =)

**Comment by acvetkov** [comment]
https://github.com/acvetkov/sinon-chrome/pull/17

**Comment by joanne254** [comment]
Great. Thanks!

**Comment by acvetkov** [comment]
@joanne254 update your sinon-chrome deps.
```
npm i sinon-chrome@1.0.3 --save-dev
```

It should works.

**Comment by acvetkov** [comment]
Fell free to create pull request =)
