### ISSUE TITLE
Link to built sinon-chrome.js in README is invalid

### ISSUE THREAD

**Issue by abloom** [acvetkov/sinon-chrome#24]
The link to the pre-built `sinon-chrome.js` in the README is no longer valid.

Would it be possible to include a final `sinon-chrome.js` file in each published npm module? Right now I'm finding it tricky to have consistency with `sinon-chrome.js` in both my Node.js and and PhantomJS tests. It would be very convenient to use the same npm install for both environments without having to run webpack on my own.

**Comment by acvetkov** [comment]
Hi.

Thanks for issue. I will fix readme file in few hours. Now you can take actual sinon-chrome bundle from release page

**Comment by acvetkov** [comment]
Link for to `sinon-chrome` bundle is correct.
I have excluded `sinon-chrome` bundle from git index last month, because it mess up git diffs.
