### ISSUE TITLE
Google Apps

### ISSUE THREAD

**Issue by zkendall** [acvetkov/sinon-chrome#32]
Any plan to add [Apps](https://developer.chrome.com/apps/api_index) features? For example: https://developer.chrome.com/apps/fileSystem

**Comment by acvetkov** [comment]
@zkendall, hi!

Yes, I want to support apps features.
Do you want to create pr?

**Comment by zkendall** [comment]
Cool. Well, I'm pretty new to the JS ecosystem. Currently I'm manually mocking out what I need. If that ends up not being enough, I'll dip into sinon and contribute it here.

**Comment by acvetkov** [comment]
@zkendall Hi.

Good news for you.

Since v.2.0 we have supported chrome apps api.

```js
const chrome = require('sinon-chrome/apps');
```
