### ISSUE TITLE
How to test event listeners on the port object?

### ISSUE THREAD

**Issue by cauboy** [acvetkov/sinon-chrome#34]
Hey,
thanks a lot for this repo. It really helps. 
One question: Is there actually a way to test event listeners on the port object. How would one test the following code?

```javascript
Chrome.runtime.onConnect.addListener(function(port) {
  port.onDisconnect(function() { console.log('Port disconnected'); });
});
```

Cheers.
Clemens

**Comment by acvetkov** [comment]
@cauboy, hi!

Unfortunately, we does not support port objects.
Feel free to create pull request.

**Comment by cauboy** [comment]
Thought so, just wanted to be sure :)
