### ISSUE TITLE
Karma configuration

### ISSUE THREAD

**Issue by herodrigues** [acvetkov/sinon-chrome#37]
I know that there is a karma sinon-chrome wrap, but I could not find any reliable solution to what I'm looking for. I'm getting this error:

```
Chrome 52.0.2743 (Linux 0.0.0) ERROR
  Uncaught TypeError: Cannot read property 'create' of undefined
  at node_modules/sinon-chrome/dist/sinon-chrome.latest.js:7537
```

My spec file
```js
  describe('chrome.*', function () {
    beforeEach(function () {
      console.log(chrome);
    });

    it('should open a new tab', function () {
      // chrome.tabs.create({});
      // expect(chrome.tabs.create.called).toBe(true);
    });
  });
```

I installed sinon-chrome and karma-sinon-chrome via npm. My karma config file:

```js
  frameworks: [
      'jasmine',
      'requirejs',
      'sinon-chrome'
    ],

    // list of files / patterns to load in the browser
    files: [
      { pattern: 'src/**/*.js', included: false },
      { pattern: 'test/*-spec.js', included: false },
      'require.conf.js'
    ],

    // list of files to exclude
    exclude: [
      'src/vendor/**/*.js'
    ],

    // plugins
    plugins: [
      'karma-jasmine',
      'karma-chrome-launcher',
      'karma-requirejs',
      'karma-sinon-chrome'
      //'karma-coverage'
    ],
```

**Comment by acvetkov** [comment]
Hi, @herodrigues .
https://github.com/9joneg/karma-sinon-chrome/issues/3

**Comment by 9joneg** [comment]
> Sinon.JS v1.x as source doesn't work with AMD loaders / RequireJS / Webpack / Browserify.

> This has been resolved in Sinon v2.x

[https://github.com/sinonjs/sinon#important-sinon-v1x-does-not-work-with-amdcommonjs-bundlers](https://github.com/sinonjs/sinon#important-sinon-v1x-does-not-work-with-amdcommonjs-bundlers)

**Comment by herodrigues** [comment]
So, there is no solution yet?

**Comment by acvetkov** [comment]
So, we should wait sinon 2 stable version (now 2.0.0-pre.2).

**Comment by herodrigues** [comment]
Thanks @acvetkov.

I followed your instructions here: https://github.com/acvetkov/sinon-chrome/issues/11

**Comment by acvetkov** [comment]
https://github.com/acvetkov/sinon-chrome/issues/11
