### ISSUE TITLE
Please consider supporting Firefox's WebExtensions

### ISSUE THREAD

**Issue by Standard8** [acvetkov/sinon-chrome#40]
Firefox is currently implementing web extensions - these are pretty much the same as the `chrome.*`, although there are a few differences.

Firefox has created the `browser.*` namespace which is virtually the same as the `chrome.*` space. There are two differences:

- `browser.*` will gain Firefox specific extensions.
- `browser.*` uses promises rather the callbacks.

More information:

- https://wiki.mozilla.org/WebExtensions#Namespacing
- https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Using_the_JavaScript_APIs

**Comment by vitalets** [comment]
@Standard8 great point!

**Comment by kumar303** [comment]
One way that would allow this library to keep up with new APIs and API changes (which are probably a bit rare) is to parse schema files. Had you considered that?

Here is an example of the bookmarks API:
* Chrome: https://chromium.googlesource.com/chromium/src/+/master/chrome/common/extensions/api/bookmarks.json
* Firefox: http://searchfox.org/mozilla-central/source/browser/components/extensions/schemas/bookmarks.json

All of Firefox's extension schemas:
* Internal APIs (no UI): http://searchfox.org/mozilla-central/source/toolkit/components/extensions/schemas
* browser UI extensions: http://searchfox.org/mozilla-central/source/browser/components/extensions/schemas

Parsing schema files would also make the behavior of the mocks very exact.

**Comment by acvetkov** [comment]
@Standard8 hi.

Why you can not use `sinon-chrome` for FF web-extensions testing?

```js
global.browser = require('sinon-chrome');

before(function() {
  browser.tabs.query.yields([]);
  // or
  browser.tabs.query.returns(Promise.resolve([]));
});
```

**Comment by Standard8** [comment]
@acvetkov Whilst that is possible, the browser namespace has different APIs to the chrome namespace, so simply duplicating the chrome one isn't likely to be correct - and could lead to code that runs tests fine still being wrong as the API isn't there.

**Comment by acvetkov** [comment]
@Standard8 Ok. I'll implement schema files for chrome and FF webextensions

**Comment by acvetkov** [comment]
`sinon-chrome` has supported webextensions api since `2.1.0` version.
