### ISSUE TITLE
How to test if extension is loadable

### ISSUE THREAD

**Issue by CrazyPython** [acvetkov/sinon-chrome#41]
loadable = on "reload" no yellow box with error

**Comment by acvetkov** [comment]
@CrazyPython, hi.

What do you mean? Are you talk about invalid manifest?
Can you attach an example?

**Comment by CrazyPython** [comment]
@acvetkov yes, invalid manifest, esp. no file present

**Comment by acvetkov** [comment]
Probably, you missunderstand something.
`sinon-chrome` does not validate manifest, it's helper tool for testing your code.

**Comment by CrazyPython** [comment]
@acvetkov what other tool to use then? or can this be implemented?

**Comment by vitalets** [comment]
@CrazyPython 
I think the first approach can be verifying that manifest is correct json file, e.g.
```js
var manifest = fs.readFileSync('./src/manifest.json');
try {
  JSON.parse(manifest);
} catch () {
  console.log('Manifest error', manifest);
}
```

**Comment by CrazyPython** [comment]
@vitalets That is obvious - but surely if chrome can't load it sinon also can't?

**Comment by vitalets** [comment]
> but surely if chrome can't load it sinon also can't?
I think not. Sinon-chrome currently does not use manifest now.
