### ISSUE TITLE
chrome.js is missing?

### ISSUE THREAD

**Issue by zhaiduo** [acvetkov/sinon-chrome#46]
It seems chrome.js not in sinon-chrome folder, where I can find this file?

` page.injectJs(node_modules + 'sinon-chrome/chrome.js');`

I need it to test chrome extension. Thanks for any help~

**Comment by acvetkov** [comment]
@zhaiduo, hi.

You have two ways:

1. Checkout new version `2.1.0`.  `node_modules/sinon-chrome/dist`

a. `sinon-chrome.min.js` - stable chrome extensions api
b. `sinon-chrome-apps.min.js` - stable chrome apps api
c. `sinon-chrome-webextensions.min.js` - stable Firefox webextensions api

2. Download budle from [release](https://github.com/acvetkov/sinon-chrome/releases/tag/2.1.0) page
