### ISSUE TITLE
Dist files not included in npm download for 2.x releases

### ISSUE THREAD

**Issue by Standard8** [acvetkov/sinon-chrome#48]
Since 2.x the dist/ files don't appear to be in the releases when installing via npm. Was there a specific reason for this, or has this been missed?

**Comment by acvetkov** [comment]
@Standard8, I have moved this files to bundle dir.

```
|--sinon-chrome
  |--api
  |--apps
  |--bundle
    |--sinon-chrome.min.js
    |--sinon-chrome-apps.min.js
    |--sinon-chrome-webextensions.min.js
```

**Comment by Standard8** [comment]
@acvetkov thanks, not sure how I missed that!
