### ISSUE TITLE
how to handle the global variable in typescript?

### ISSUE THREAD

**Issue by Alino** [acvetkov/sinon-chrome#51]
if I use
```javascript
global.chrome = chrome
```

typescript gives me error ```error TS2304: Cannot find name 'global'.```

but if I declare global like this
```javascript
let global = {};
global.chrome = chrome
```

My tests will fail, because ```chrome``` is not defined on the separate file that I am writing tests for.

**Comment by Alino** [comment]
ok I was able to work around this by doing this

```
declare var global: any;
global.chrome = chrome
```

**Comment by acvetkov** [comment]
Hi, @Alino .

`global` is Node.js [global](https://nodejs.org/api/globals.html#globals_global) object.
You should use `window` object, if you run your tests under browser.
