### ISSUE TITLE
Chrome Application runtime

### ISSUE THREAD

**Issue by sagorshkov** [acvetkov/sinon-chrome#53]
Hello. I'm using your awesome module to mock chrome application object in my tests and I've got an issue. Method **chrome.runtime.getManifest()** returns undefined, but there is something like this in my code: **chrome.runtime.getManifest().version**. I've tried to redefine **getManifest** method but It's not possible because of the descriptor of this property is:

> `Object.getOwnPropertyDescriptor(chrome.runtime, 'getManifest')`
> `Object {set: undefined, enumerable: false, configurable: false, get: function}`
> `configurable:false`
> `enumerable:false`
> `get:function get()`
> `set:undefined`
> `__proto__:Object`

Is there a way to compel getManifest() return some objects?
Thanks in advance.

**Comment by acvetkov** [comment]
@sagorshkov hi!

You should not redefine `getManifest`, it's already sinon stub without predefined behavior.
Just define returning value

```js
chrome.runtime.getManifest.returns({
   version: '0.0.1',
   // other important props
});
```

**Comment by sagorshkov** [comment]
Awesome! Thank you.
