### ISSUE TITLE
chrome.storage.local.get never executes

### ISSUE THREAD

**Issue by warent** [acvetkov/sinon-chrome#55]
I'm testing with Jest 19.0.2, and when I try to use:

chrome.storage.local.get(key, val => console.log(val))

It will never actually execute the anonymous function and log anything. Is this expected behavior?

**Comment by acvetkov** [comment]
@warent hi!

`chrome.storage.local.get` is sinon [stub](http://sinonjs.org/releases/v2.1.0/stubs/), you should define behavior.

```js
chrome.storage.local.get.yields('result');
// or
chrome.storage.local.get.withArgs('key').yields('value_for_key');
```

**Comment by warent** [comment]
That's it. Sinon is new to me; definitely will do some reading. Thank you for the help :)
