### ISSUE TITLE
Sinon-chrome with Jasmine?

### ISSUE THREAD

**Issue by kaimdx** [acvetkov/sinon-chrome#58]
I am fairly new to (Chrome extension) testing and started with Jasmine (https://jasmine.github.io/). Then I realised that I need to 'stub' out many Chrome API functions for testing and found sinon-chrome, which is great. Is it possible to use sinon-chrome together with jasmine (and how?), or you have to choose one between sinon and jasmine?

**Comment by acvetkov** [comment]
Hi, @kaimdx 
What problem you have with jasmine? You can use `sinon-chrome` stubs with jasmine assertations. I think it should works.

**Comment by kaimdx** [comment]
No, I don't have any specific problem yet. I am just wondering if the two would work together. After reading a bit more, I came to the same conclusion that the two should work together (which is a good news for me). I will try it out now and let you know if I have any problem.

**Comment by acvetkov** [comment]
I will be happy to help
