### ISSUE TITLE
Usage example: second test fails

### ISSUE THREAD

**Issue by phongvis** [acvetkov/sinon-chrome#59]
I forked the project and tried to run the usage example but the second test is failed at `assert.calledOnce(chrome.browserAction.setBadgeText);`. The callback in `chrome.tabs.query(params, callback);` isn't invoked. 

Here is my fork: https://github.com/phongvis/sinon-chrome with the following changes:
- package.json: add `test-background` option for `npm-run` and install jsdom
- the extension files are placed at `examples/src`
- the test file is `examples/background.test.js` also in examples

Could you have a check? Thanks.

**Comment by herodrigues** [comment]
See https://github.com/acvetkov/sinon-chrome/issues/42
