### ISSUE TITLE
Is it possible to run sinon-chrome test without node.js?

### ISSUE THREAD

**Issue by kaimdx** [acvetkov/sinon-chrome#60]
I am currently learning to test my extension using Jasmine following this setup, which doesn't require node.js:
https://gist.github.com/stevenqzhang/333fd0b2bca201aabaa40c7b63a74296

All the sinon-chrome examples seem to run test using node.js. Is it possible at all to run sinon-chrome test without node.js? If so, any example will be great.

Thanks,

**Comment by acvetkov** [comment]
Hi.

You can use [sinon-chrome.min.js](https://github.com/acvetkov/sinon-chrome/releases)
