### ISSUE TITLE
Question: How to send response messages, if my code sends messages

### ISSUE THREAD

**Issue by kangaro0** [acvetkov/sinon-chrome#62]
Hey,

I'm trying to test my extension's popup code. The popup has a init function which catches data from the background page. In order to do that the popup sends a request to the background page via `chrome.runtime.sendMessage( ... )`. 

Now I tried different approaches how to 'fake' the response from the background page, currently I'm trying this [approach](https://github.com/kangaro0/Freewar-Helper/blob/dev/test/popup.test.js). 

But the the listener doesn't get called, once the Popup sends the request... 
What am I doing wrong?

**Comment by acvetkov** [comment]
@kangaro0 Hi.

Chrome api is just stubs without any behavior.
You should manually trigger event in your case.

```js
chrome.runtime.onMessage.addListener(functionSpy);

chrome.runtime.onMessage.trigger(params);

assert.calledOnce(functionSpy.withArgs(params));
```

**Comment by kangaro0** [comment]
Alright. I was on the wrong path here....
Thanks!
