### ISSUE TITLE
Phantom JS 2.0.0 seems to ignore AssertionError

### ISSUE THREAD

**Issue by dbaba** [acvetkov/sinon-chrome#7]
Hi,
I've been using sinon-chrome 0.2.1 with PhantomJS 2.0.0 on node v0.12.6 and I got stuck on an issue where PhantomJS silently ignored chai's assertion errors, i.e. tests were always successful...
Fortunately, I've been able to fix it by overriding a function `evaluate` in a webpage object  created by phantomjs but I'm not sure if it is a right resolution.

Please review my workaround when you have time. Any suggestion is appreciated.

The [gist](https://gist.github.com/dbaba/7d6e96f8d8ebca602306) is the workaround (deriving from beforeeach.js), adding code snip from line 8 to 43. I modified the function wrapper string at line 42. You can find the original code in [phantomjs webpage.js](https://github.com/ariya/phantomjs/blob/master/src/modules/webpage.js#L386).

Other test-use dependencies are:
* sinon 1.10.0
* chai 3.3.0
* mocha 2.0.1

**Comment by acvetkov** [comment]
@dbaba Is this issue actual?
