### ISSUE TITLE
v2.2.2 is broken

### ISSUE THREAD

**Issue by crimx** [acvetkov/sinon-chrome#70]
It seems like the Github project is published to NPM. `require('sinon-chrome/extensions')` and `require('sinon-chrome/webextensions')` break on v2.2.2.

And #69 is not correctly built.

**Comment by acvetkov** [comment]
just a minute

**Comment by acvetkov** [comment]
try this one
https://www.npmjs.com/package/sinon-chrome v2.2.3

**Comment by crimx** [comment]
Thanks @acvetkov . #69 is fixed but `require('sinon-chrome/extensions')` and `require('sinon-chrome/webextensions')` are still break.

I think `"main": "out/index.js"` in package.json should be changed to `"main": "index.js"`.

And publish the NPM package within `./out`.

**Comment by acvetkov** [comment]
Fantastic fail. 

I will fix tomorrow.
