### ISSUE TITLE
Proposal: module for WebExtensions schemas

### ISSUE THREAD

**Issue by asamuzaK** [acvetkov/sinon-chrome#89]
Hi,
I created a module that fetched and saved the WebExtensions schema directly from hg.mozilla.org.
[asamuzaK/webext-schema: WebExtensions schemas fetched from hg.mozilla.org](https://github.com/asamuzaK/webext-schema)

It is still under development, but I think that with this module, sinon-chrome will no longer has to worry about WebExtensions schemas.
And this module should fix #63 and #87.

At this time, I can't verify that it actually works with sinon-chrome for the #88 issue, but as far as I've tried, it seems to work fine.
Test code [webext-schema/schema.test.js at master · asamuzaK/webext-schema](https://github.com/asamuzaK/webext-schema/blob/master/test/schema.test.js#L241)

Please send me your feedback on whether or not to implement this module to sinon-chrome.
If you think it's acceptable, I'll send a PR later.

Thanks.

**Comment by ariasuni** [comment]
Any news about this? I can’t use `sinon-chrome` because it doesn’t support [`browser.menus`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/menus), for example.

**Comment by stoically** [comment]
My [`webextensions-schema`](https://github.com/stoically/webextensions-schema) might also be of interest, it automatically fetches the latest stable schema. I've built it as basis for [`webextensions-api-mock`](https://github.com/stoically/webextensions-api-mock).

**Comment by asamuzaK** [comment]
I'll close this issue.
[webext-schema](https://github.com/asamuzaK/webext-schema) now creates the stubbed browser API
