### ISSUE TITLE
`chrome.alarms.getAll()` returns `undefined` instead of array of alarms

### ISSUE THREAD

**Issue by jeremiahlee** [acvetkov/sinon-chrome#90]
[`chrome.alarms.getAll()`](https://developer.chrome.com/extensions/alarms#method-getAll) should return an array of alarms. However, it is returning `undefined` using v3.0.1.

```javascript
const chrome = require("sinon-chrome/extensions");

(async () => {
    let alarms = await chrome.alarms.getAll();
    console.log(alarms); // `undefined`

    await chrome.alarms.create("testAlarm", {
        delayInMinutes: 15
    });

    alarms = await chrome.alarms.getAll();
    console.log(alarms); // `undefined`

    let alarm = await chrome.alarms.get("testAlarm");
    console.log(alarm); // `undefined`
})();
```

**Comment by jeremiahlee** [comment]
Apologies. I did not realize these were API stubs, not for faking behavior.

**Comment by JackZong** [comment]
> Apologies. I did not realize these were API stubs, not for faking behavior.

so, is that all of the returning should be mocked by self? 
And all of the returning should be mocked by `.returns()` ? is it right? thanks
